# Generated by Django 5.2.8 on 2025-11-26 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("product", "0019_alter_variant_options_alter_variant_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="variant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="product.variant",
            ),
            preserve_default=False,
        ),
    ]
