# Generated by Django 5.2.8 on 2025-11-26 06:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cart_variant"),
        ("product", "0019_alter_variant_options_alter_variant_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user", "variant")},
        ),
    ]
