# Generated by Django 5.2.8 on 2025-11-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
    ]
