# Generated by Django 5.2.8 on 2025-12-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_remove_cart_coupon_cartappliedcoupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartappliedcoupon",
            name="discount_applied",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
