# Generated by Django 5.2.8 on 2025-12-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_cartappliedcoupon_discount_applied"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartappliedcoupon",
            name="discount_applied",
        ),
    ]
