# Generated by Django 5.2.8 on 2025-12-10 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0022_alter_order_payment_method"),
        ("payment", "0002_payment_order_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="order.order",
            ),
        ),
    ]
