# Generated by Django 5.2.8 on 2025-11-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="style",
            name="is_deleted",
            field=models.BooleanField(default=True),
        ),
    ]
