# Generated by Django 5.2.8 on 2025-11-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_style_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="style",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
