# Generated by Django 5.2.8 on 2025-11-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_style_is_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="style",
            options={"ordering": ["is_deleted", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="product",
            name="tshirt_type",
        ),
        migrations.AddField(
            model_name="product",
            name="style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="product.style",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
