# Generated by Django 5.2.8 on 2025-11-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_style_options_remove_product_tshirt_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["is_active", "created_at"]},
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
