# Generated by Django 5.2.8 on 2025-11-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_variants"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Variants",
            new_name="Variant",
        ),
    ]
