# Generated by Django 5.2.8 on 2025-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_rename_variants_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="base_color",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="variant",
            name="size",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
