# Generated by Django 5.2.8 on 2025-11-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_product_base_color_alter_variant_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="size",
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.UniqueConstraint(
                fields=("product", "size"), name="unique_product_size"
            ),
        ),
    ]
