# Generated by Django 5.2.8 on 2025-11-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_variant_size_variant_unique_product_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["is_active", "-created_at"]},
        ),
    ]
