# Generated by Django 5.2.8 on 2025-11-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-is_active", "-created_at"]},
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=" ", upload_to="products/"),
            preserve_default=False,
        ),
    ]
