# Generated by Django 5.2.8 on 2025-11-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_productimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimages",
            name="image_public_id",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
