# Generated by Django 5.2.8 on 2025-11-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_productimages_image_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_public_id",
            field=models.CharField(default=" ", max_length=255),
            preserve_default=False,
        ),
    ]
