# Generated by Django 5.2.8 on 2025-11-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_product_image_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
