# Generated by Django 5.2.8 on 2025-11-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="size",
            field=models.CharField(
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "2X Large"),
                ],
                max_length=10,
            ),
        ),
    ]
