# Generated by Django 5.2.8 on 2025-11-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_alter_variant_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variant",
            options={"ordering": ["product", "size"]},
        ),
    ]
