# Generated by Django 5.2.8 on 2025-11-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_alter_variant_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variant",
            options={},
        ),
        migrations.AlterField(
            model_name="variant",
            name="size",
            field=models.CharField(max_length=10),
        ),
    ]
