# Generated by Django 5.2.8 on 2025-12-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0019_alter_variant_options_alter_variant_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="uuid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
