# Generated by Django 5.2.8 on 2025-12-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0020_product_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.CharField(blank=True, default=" ", max_length=20),
            preserve_default=False,
        ),
    ]
