# Generated by Django 5.2.8 on 2025-12-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0021_alter_product_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
