# Generated by Django 5.2.8 on 2025-12-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_variant_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variant",
            name="is_active",
        ),
    ]
