# Generated by Django 5.2.8 on 2025-12-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0023_remove_variant_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="base_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("white", "White"),
                    ("black", "Black"),
                    ("beige", "Beige"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("grey", "Grey"),
                    ("yellow", "Yellow"),
                    ("brown", "Brown"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                ],
                max_length=20,
            ),
        ),
    ]
