# Generated by Django 5.2.8 on 2025-12-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0024_alter_product_base_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="size",
            field=models.CharField(
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                    ("XXXL", "XXXL"),
                ],
                max_length=10,
            ),
        ),
    ]
