# Generated by Django 5.2.8 on 2025-12-24 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0025_alter_variant_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variant",
                to="product.product",
            ),
        ),
    ]
