# Generated by Django 5.2.8 on 2025-12-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransactions",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
