# Generated by Django 5.2.8 on 2025-12-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_wallettransactions_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransactions",
            name="transaction_type",
            field=models.CharField(
                choices=[("credit", "Credit"), ("debit", "Debit")], max_length=30
            ),
        ),
    ]
