# Generated by Django 5.2.8 on 2025-12-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_wallettransactions_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="wallettransactions",
            name="txn_source",
            field=models.CharField(
                choices=[
                    ("reward", "Reward"),
                    ("online", "Online"),
                    ("shopping", "Shopping"),
                    ("refund", "Refund"),
                ],
                max_length=100,
            ),
        ),
    ]
