# Generated by Django 5.2.8 on 2026-01-06 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_review_unique_together'),
        ('wallet', '0004_alter_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderitems'),
        ),
    ]
