# Generated by Django 5.2.8 on 2026-01-06 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_review_unique_together'),
        ('wallet', '0005_wallettransactions_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
