# Generated by Django 5.2.8 on 2025-12-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="category",
            new_name="style",
        ),
    ]
