# Generated by Django 5.2.8 on 2025-12-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0002_rename_category_offer_style"),
        ("product", "0023_remove_variant_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.style",
            ),
        ),
    ]
