# Generated by Django 5.2.8 on 2025-12-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0003_alter_offer_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="uuid",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
