# Generated by Django 5.2.8 on 2025-12-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0004_offer_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="discount",
            field=models.IntegerField(),
        ),
    ]
