# Generated by Django 5.2.8 on 2025-11-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_options_user_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-is_active", "-created_at"]},
        ),
    ]
