# Generated by Django 5.2.8 on 2025-11-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="user",
        ),
        migrations.AddField(
            model_name="otp",
            name="email",
            field=models.EmailField(default=" ", max_length=254),
            preserve_default=False,
        ),
    ]
