# Generated by Django 5.2.8 on 2025-11-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_otp_user_otp_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_img_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
