# Generated by Django 5.2.8 on 2025-11-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_user_profile_img_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_img_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
