# Generated by Django 5.2.8 on 2025-11-26 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_user_profile_img_public_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField()),
                ("phone", models.CharField(max_length=15)),
                (
                    "second_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address_line", models.TextField()),
                ("city", models.CharField()),
                ("state", models.CharField()),
                ("pincode", models.CharField(max_length=6)),
                ("type", models.CharField(max_length=15)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
