# Generated by Django 5.2.8 on 2025-11-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
