# Generated by Django 5.2.8 on 2025-11-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_address_is_deleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="is_deleted",
            new_name="is_active",
        ),
    ]
