# Generated by Django 5.2.8 on 2025-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_rename_is_deleted_address_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
