# Generated by Django 5.2.8 on 2025-12-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_address_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="address",
            name="second_phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
