# Generated by Django 5.2.8 on 2025-12-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_address_phone_alter_address_second_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="pincode",
            field=models.CharField(max_length=15),
        ),
    ]
