# Generated by Django 5.2.8 on 2025-12-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0007_alter_coupon_status"),
        ("user", "0015_alter_address_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_coupons",
            field=models.ManyToManyField(
                related_name="saved_users", to="coupon.coupon"
            ),
        ),
    ]
