# Generated by Django 5.2.8 on 2025-12-15 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_user_saved_coupons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="referral_reward",
        ),
        migrations.AlterField(
            model_name="user",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
