# Generated by Django 5.2.8 on 2025-12-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="variant_id",
            new_name="product_id",
        ),
    ]
