# Generated by Django 5.2.8 on 2025-12-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_rename_variant_id_wishlist_product_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="product_id",
            new_name="product",
        ),
    ]
