# Generated by Django 5.2.8 on 2025-12-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_rename_product_id_wishlist_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="size",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
