# Generated by Django 5.2.8 on 2025-12-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0023_remove_variant_is_active"),
        ("user", "0023_alter_wishlist_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "product")},
        ),
    ]
