# Generated by Django 5.2.8 on 2025-11-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_address_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sub_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
