# Generated by Django 5.2.8 on 2025-11-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_sub_total"),
        ("product", "0019_alter_variant_options_alter_variant_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="order",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="order.order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitems",
            name="variant",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.variant",
            ),
            preserve_default=False,
        ),
    ]
