# Generated by Django 5.2.8 on 2025-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_orderitems_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="delivery_fee",
            new_name="grand_total",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="discount_amount",
            new_name="total_delivery_fee",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="tax_amount",
            new_name="total_discount",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_amount",
            new_name="total_tax",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="order",
            name="total_items",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitems",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitems",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitems",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("COD", "Cash on Delivery"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="orderitems",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitems",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
