# Generated by Django 5.2.8 on 2025-11-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_rename_delivery_fee_order_grand_total_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_delivery_fee",
            new_name="delivery_total",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_discount",
            new_name="discount_total",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_tax",
            new_name="tax_total",
        ),
    ]
