# Generated by Django 5.2.8 on 2025-11-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_rename_total_delivery_fee_order_delivery_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Order Initiated"),
                    ("PLACED", "Order Placed"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED", "Returned"),
                ],
                default="INITIATED",
                max_length=30,
            ),
        ),
    ]
