# Generated by Django 5.2.8 on 2025-11-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_alter_orderitems_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitems",
            name="out_for_delivery_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitems",
            name="placed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitems",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Order Initiated"),
                    ("PLACED", "Order Placed"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out For Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED", "Returned"),
                ],
                default="INITIATED",
                max_length=30,
            ),
        ),
    ]
