# Generated by Django 5.2.8 on 2025-11-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_orderitems_delivered_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="order_item_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
