# Generated by Django 5.2.8 on 2025-12-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_orderitems_order_item_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitems",
            old_name="order_item_id",
            new_name="uuid",
        ),
    ]
