# Generated by Django 5.2.8 on 2025-12-02 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0012_rename_order_item_id_orderitems_uuid"),
        ("user", "0013_alter_address_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_date", models.DateField(blank=True, null=True)),
                ("reason", models.CharField(max_length=255)),
                ("comments", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PICKUP_SCHEDULED", "Pickup Scheduled"),
                            ("PICKED_UP", "Picked Up"),
                            ("REFUND_INITIATED", "Refund Initiated"),
                            ("REFUNDED", "Refund Completed"),
                        ],
                        default="REQUESTED",
                        max_length=30,
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock_updated", models.BooleanField(default=False)),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_request",
                        to="order.orderitems",
                    ),
                ),
                (
                    "pickup_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.address"
                    ),
                ),
            ],
        ),
    ]
