# Generated by Django 5.2.8 on 2025-12-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_returnrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="returnrequest",
            name="description",
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
