# Generated by Django 5.2.8 on 2025-12-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0014_remove_returnrequest_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="product_image1",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="product_image2",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="product_image3",
            field=models.URLField(blank=True, null=True),
        ),
    ]
