# Generated by Django 5.2.8 on 2025-12-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_returnrequest_product_image1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="pickedup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="pickup_scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PICKUP_SCHEDULED", "Pickup Scheduled"),
                    ("PICKED_UP", "Picked Up"),
                    ("REFUNDED", "Refund Completed"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
    ]
