# Generated by Django 5.2.8 on 2025-12-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0016_returnrequest_approved_at_returnrequest_pickedup_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="uuid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="uuid",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
