# Generated by Django 5.2.8 on 2025-12-04 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0017_returnrequest_uuid_alter_orderitems_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="quantity",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ]
            ),
        ),
    ]
