# Generated by Django 5.2.8 on 2025-12-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0018_alter_orderitems_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="returnrequest",
            old_name="pickup_scheduled_at",
            new_name="pickup_scheduled_for",
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="pickup_scheduled_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
