# Generated by Django 5.2.8 on 2025-12-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "order",
            "0019_rename_pickup_scheduled_at_returnrequest_pickup_scheduled_for_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="uuid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
