# Generated by Django 5.2.8 on 2025-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0020_order_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Order Initiated"),
                    ("PLACED", "Order Placed"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out For Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED", "Returned"),
                    ("REFUNDED", "Refunded"),
                ],
                default="INITIATED",
                max_length=30,
            ),
        ),
    ]
