# Generated by Django 5.2.8 on 2025-12-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0021_alter_orderitems_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COD", "Cash on Delivery"),
                    ("ONLINE_PAYMENT", "Online Payment"),
                    ("WALLET", "Wallet"),
                ],
                max_length=30,
            ),
        ),
    ]
