# Generated by Django 5.2.8 on 2025-12-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0007_alter_coupon_status"),
        ("order", "0022_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_applied",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coupon.coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_discount_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
