# Generated by Django 5.2.8 on 2025-12-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0023_order_coupon_applied_order_coupon_discount_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="tax_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
