# Generated by Django 5.2.8 on 2025-12-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0024_alter_orderitems_tax_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="tax_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
