# Generated by Django 5.2.8 on 2025-12-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0025_alter_order_tax_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="coupon_discount_amount",
            new_name="coupon_discount_total",
        ),
        migrations.AddField(
            model_name="orderitems",
            name="coupon_discount_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
