# Generated by Django 5.2.8 on 2025-12-24 11:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0027_alter_orderitems_variant_review"),
        ("product", "0026_alter_variant_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("product", "user")},
        ),
    ]
