# Generated by Django 5.2.8 on 2025-12-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("FLAT", "Flat"), ("PERCENTAGE", "Percentage")],
                        max_length=20,
                    ),
                ),
                ("discount_value", models.IntegerField()),
                (
                    "min_purchase_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("usage_limit", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
