# Generated by Django 5.2.8 on 2025-12-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0002_alter_coupon_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="usage_remaining",
            field=models.IntegerField(default=0),
        ),
    ]
