# Generated by Django 5.2.8 on 2025-12-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0004_alter_coupon_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="min_purchase_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
