# Generated by Django 5.2.8 on 2025-12-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0005_alter_coupon_min_purchase_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit",
            field=models.IntegerField(default=-1),
        ),
    ]
