# Generated by Django 5.2.8 on 2025-12-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0006_alter_coupon_usage_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("EXPIRED", "Expired"),
                    ("LIMIT_REACHED", "Usage Limit Reached"),
                ],
                default="INACTIVE",
                max_length=50,
            ),
        ),
    ]
