# Generated by Django 5.2.8 on 2025-12-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0008_couponusage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="status",
        ),
    ]
